language: cpp

addons:
  postgresql: "9.3"

compiler:
 - clang
 - gcc

env:
  matrix:
   - XMLPARSER="libxml2"
   - XMLPARSER="ptree"

before_install:
 - sudo add-apt-repository -y ppa:boost-latest/ppa
 - sudo add-apt-repository -y ppa:ubuntugis/ubuntugis-unstable
 - sudo apt-get update -qq
 - sudo apt-get install -y make valgrind libgdal-dev boost1.55 python-nose libicu-dev libpng-dev libjpeg-dev libtiff-dev libwebp-dev libz-dev libfreetype6-dev libxml2-dev libproj-dev libcairo-dev python-cairo-dev libsqlite3-dev

script:
 - ./configure CXX=${CXX} CC=${CC} XML_PARSER=$XML_PARSER DEBUG=False DEMO=True BENCHMARK=True BINDINGS='python' CPP_TESTS=True CAIRO=True FAST=True
 - JOBS=3 make
 - make test-local
 - sudo make install
 - make grind

notifications:
  irc:
    channels:
      - "irc.freenode.org#mapnik"
    use_notice: true
