language: cpp

compiler:
 - gcc
 # disabled to due https://github.com/mapnik/mapnik/issues/2235
 #- clang

# http://about.travis-ci.org/blog/2013-11-29-postgresql-92-93-now-available/
addons:
  postgresql: "9.3"

before_install:
 # we need at least g++-4.7 for c++11 features
 - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
 # grab more recent gdal/proj
 - sudo add-apt-repository -y ppa:ubuntugis/ubuntugis-unstable
 # more recent boost
 - sudo add-apt-repository -y ppa:mapnik/boost
 # upgrade compilers
 - wget -O - http://llvm.org/apt/llvm-snapshot.gpg.key|sudo apt-key add -
 - sudo bash -c "echo 'deb http://llvm.org/apt/precise/ llvm-toolchain-precise main' > /etc/apt/sources.list.d/llvm-nightly.list"
 - sudo bash -c "echo 'deb-src http://llvm.org/apt/precise/ llvm-toolchain-precise main' >> /etc/apt/sources.list.d/llvm-nightly.list"
 - sudo apt-get update -y
 - sudo apt-get install -y gcc-4.8 g++-4.8
 - sudo apt-get install clang-3.5 clang-3.5-doc libclang-common-3.5-dev libclang-3.5-dev libclang1-3.5 libclang1-3.5-dbg libllvm-3.5-ocaml-dev libllvm3.5 libllvm3.5-dbg lldb-3.5 llvm-3.5 llvm-3.5-dev llvm-3.5-doc llvm-3.5-examples llvm-3.5-runtime clang-modernize-3.5 clang-format-3.5 python-clang-3.5 lldb-3.5-dev
 - sudo apt-get install -y make libboost-dev libboost-filesystem-dev libboost-program-options-dev libboost-python-dev libboost-regex-dev libboost-system-dev libboost-thread-dev python-nose libicu-dev libpng-dev libjpeg-dev libtiff-dev libwebp-dev libz-dev libfreetype6-dev libxml2-dev libproj-dev libcairo-dev python-cairo-dev libsqlite3-dev
 - wget http://mapnik.s3.amazonaws.com/deps/harfbuzz-0.9.24.tar.bz2
 - tar xf harfbuzz-0.9.24.tar.bz2
 - cd harfbuzz-0.9.24
 - ./configure && make && sudo make install
 - sudo ldconfig
 - cd ../
 - createdb template_postgis
 - psql -c "CREATE EXTENSION postgis" template_postgis

install:
# - if [ "${CXX}" = 'g++' ]; then export CXX="g++-4.8" && export CC="gcc-4.8"; fi;
 - ./configure CXX=clang++-3.5 CC=clang-3.5  CUSTOM_CXXFLAGS="-flto" CUSTOM_LDFLAGS="-flto" DEMO=False BINDINGS=${BINDINGS} BENCHMARK=${BENCHMARK} CPP_TESTS=${CPP_TESTS} CAIRO=True FAST=True || cat config.log
 - JOBS=1 make

env:
  - TESTS_TO_RUN=python BINDINGS=python CPP_TESTS=false BENCHMARK=false
  - TESTS_TO_RUN=visual BINDINGS=python CPP_TESTS=false BENCHMARK=false
  - TESTS_TO_RUN=cpp BINDINGS=none CPP_TESTS=true BENCHMARK=true

before_script:
 - make test-$TESTS_TO_RUN

script:
 - if [ "${BENCHMARK}" = true ]; then make bench; fi;

notifications:
  irc:
    channels:
      - "irc.freenode.org#mapnik"
    use_notice: true
  email:
    on_success: [never]
    on_failure: [change]
