language: cpp

compiler:
 - gcc
 - clang

addons:
  postgresql: "9.3"

env:
  - TESTS_TO_RUN=python BINDINGS=python CPP_TESTS=false BENCHMARK=false DEMO=False
  - TESTS_TO_RUN=visual BINDINGS=python CPP_TESTS=false BENCHMARK=false DEMO=False
  - TESTS_TO_RUN=cpp BINDINGS=none CPP_TESTS=true BENCHMARK=true DEMO=True

before_install:
 # we need at least g++-4.7 for c++11 features
 - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
 # grab more recent gdal/proj
 # breaks due to http://trac.osgeo.org/ubuntugis/ticket/39
 #- sudo add-apt-repository -y ppa:ubuntugis/ubuntugis-unstable
 # more recent boost
 - sudo add-apt-repository -y ppa:boost-latest/ppa
 - sudo apt-get update -y
 # upgrade compilers
 - sudo apt-get install -y gcc-4.8 g++-4.8
 - sudo apt-get install -y make boost1.55 libgdal-dev python-nose libicu-dev libpng-dev libjpeg-dev libtiff-dev libwebp-dev libz-dev libfreetype6-dev libxml2-dev libproj-dev libcairo-dev python-cairo-dev libsqlite3-dev
 - wget http://mapnik.s3.amazonaws.com/deps/harfbuzz-0.9.29.tar.bz2
 - tar xf harfbuzz-0.9.29.tar.bz2
 - cd harfbuzz-0.9.29
 - ./configure && make && sudo make install
 - sudo ldconfig
 - cd ../

install:
 - if [[ "${CXX}" == 'g++' ]]; then export CXX="g++-4.8" && export CC="gcc-4.8"; fi;
 - ./configure CXX="nice ${CXX}" CC="nice ${CC}" DEMO=${DEMO} BINDINGS=${BINDINGS} BENCHMARK=${BENCHMARK} CPP_TESTS=${CPP_TESTS} CAIRO=True FAST=True
 - JOBS=3 make

before_script:
 - make test-$TESTS_TO_RUN

script:
 - if [[ "${BENCHMARK}" == true ]]; then make bench; fi;

notifications:
  irc:
    channels:
      - "irc.freenode.org#mapnik"

    use_notice: true
